language: node-js
install:
  - npm install -g codecov

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - istanbul cover node_modules\jasmine\bin\jasmine.js
  - codecov
  - curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh

git:
  depth: 10

branches:
  only:
    - master
